# Generated by Django 4.2.1 on 2023-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duetime',
            field=models.DateTimeField(),
        ),
    ]
